---
- name: Установить Python и pip
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Установить зависимости для Flask
  pip:
    name: flask
    state: present

- name: Копируем приложение Flask
  ansible.builtin.template:
    src: flask_app.py.j2
    dest: /var/www/app/app.py
    mode: '0755'

- name: Копируем systemd unit для Flask
  ansible.builtin.template:
    src: flask_app.service.j2
    dest: /etc/systemd/system/flask_app.service
  notify: Перезапустить Flask

- name: Запустить контейнер с Flask
  community.docker.docker_container:
    name: flask_app
    image: flask_app_image
    state: started
    restart_policy: always
    ports:
      - "{{ flask_port }}:5000"
    volumes:
      - /var/www/app:/app
    env:
      FLASK_ENV: production
      FLASK_APP: app.py

- name: Собираем Docker-образ Flask
  community.docker.docker_image:
    name: flask_app_image
    build:
      path: /var/www/app
    source: build
    state: present

- name: Копируем Dockerfile в приложение
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: /var/www/app/Dockerfile
